<?php

namespace ContainerCcXebBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A5PfGdEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A5PfGdE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A5PfGdE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\BookingController::bookings' => ['privates', '.service_locator.zalxbQi.App\\Controller\\BookingController::bookings()', 'getBookingControllerbookingsService', true],
            'App\\Controller\\BookingController::show' => ['privates', '.service_locator.6dAnjRq.App\\Controller\\BookingController::show()', 'getBookingControllershowService', true],
            'App\\Controller\\TripController::index' => ['privates', '.service_locator.w.bk_GH.App\\Controller\\TripController::index()', 'getTripControllerindexService', true],
            'App\\Controller\\TripController::show' => ['privates', '.service_locator.Az3_057.App\\Controller\\TripController::show()', 'getTripControllershowService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\BookingController:bookings' => ['privates', '.service_locator.zalxbQi.App\\Controller\\BookingController::bookings()', 'getBookingControllerbookingsService', true],
            'App\\Controller\\BookingController:show' => ['privates', '.service_locator.6dAnjRq.App\\Controller\\BookingController::show()', 'getBookingControllershowService', true],
            'App\\Controller\\TripController:index' => ['privates', '.service_locator.w.bk_GH.App\\Controller\\TripController::index()', 'getTripControllerindexService', true],
            'App\\Controller\\TripController:show' => ['privates', '.service_locator.Az3_057.App\\Controller\\TripController::show()', 'getTripControllershowService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\BookingController::bookings' => '?',
            'App\\Controller\\BookingController::show' => '?',
            'App\\Controller\\TripController::index' => '?',
            'App\\Controller\\TripController::show' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\BookingController:bookings' => '?',
            'App\\Controller\\BookingController:show' => '?',
            'App\\Controller\\TripController:index' => '?',
            'App\\Controller\\TripController:show' => '?',
        ]);
    }
}
