<?php

namespace ContainerCcXebBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookingControllerbookingsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zalxbQi.App\Controller\BookingController::bookings()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zalxbQi.App\\Controller\\BookingController::bookings()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'customer' => ['privates', '.errored..service_locator.zalxbQi.App\\Entity\\Customer', NULL, 'Cannot autowire service ".service_locator.zalxbQi": it needs an instance of "App\\Entity\\Customer" but this type has been excluded in "config/services.yaml".'],
            'bookings' => ['privates', 'App\\Repository\\BookingRepository', 'getBookingRepositoryService', true],
        ], [
            'customer' => 'App\\Entity\\Customer',
            'bookings' => 'App\\Repository\\BookingRepository',
        ]))->withContext('App\\Controller\\BookingController::bookings()', $container);
    }
}
