<?php

namespace ContainerCcXebBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Az3_057.App\Controller\TripController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Az3_057.App\\Controller\\TripController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trip' => ['privates', '.errored..service_locator.Az3_057.App\\Entity\\Trip', NULL, 'Cannot autowire service ".service_locator.Az3_057": it needs an instance of "App\\Entity\\Trip" but this type has been excluded in "config/services.yaml".'],
            'customers' => ['privates', 'App\\Repository\\CustomerRepository', 'getCustomerRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'trip' => 'App\\Entity\\Trip',
            'customers' => 'App\\Repository\\CustomerRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\TripController::show()', $container);
    }
}
