<?php

namespace ContainerCcXebBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Az3_057.App\Entity\Trip' shared service.
     *
     * @return \App\Entity\Trip
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Az3_057": it needs an instance of "App\\Entity\\Trip" but this type has been excluded in "config/services.yaml".');
    }
}
