<?php

namespace ContainerCcXebBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTripControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w.bk_GH.App\Controller\TripController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w.bk_GH.App\\Controller\\TripController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trips' => ['privates', 'App\\Repository\\TripRepository', 'getTripRepositoryService', true],
        ], [
            'trips' => 'App\\Repository\\TripRepository',
        ]))->withContext('App\\Controller\\TripController::index()', $container);
    }
}
