<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt_stylesheet' => [[], ['_controller' => 'web_profiler.controller.profiler::toolbarStylesheetAction'], [], [['text', '/_wdt/styles.css']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_font' => [['fontName'], ['_controller' => 'web_profiler.controller.profiler::fontAction'], [], [['text', '.woff2'], ['variable', '/', '[^/\\.]++', 'fontName', true], ['text', '/_profiler/font']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'bookings' => [['uid'], ['_route_mapping' => ['uid' => 'customer'], '_controller' => 'App\\Controller\\BookingController::bookings'], [], [['variable', '/', '[^/]++', 'uid', true], ['text', '/bookings']], [], [], []],
    'booking_show' => [['uid'], ['_route_mapping' => ['uid' => 'booking'], '_controller' => 'App\\Controller\\BookingController::show'], [], [['variable', '/', '[^/]++', 'uid', true], ['text', '/booking']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\TripController::index'], [], [['text', '/']], [], [], []],
    'trip_show' => [['slug'], ['_route_mapping' => ['slug' => 'trip'], '_controller' => 'App\\Controller\\TripController::show'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/trip']], [], [], []],
    'trip_image' => [['slug'], [], [], [['text', '.png'], ['variable', '/', '[^/\\.]++', 'slug', true], ['text', '/imgs']], [], [], []],
    'App\Controller\BookingController::bookings' => [['uid'], ['_route_mapping' => ['uid' => 'customer'], '_controller' => 'App\\Controller\\BookingController::bookings'], [], [['variable', '/', '[^/]++', 'uid', true], ['text', '/bookings']], [], [], []],
    'App\Controller\BookingController::show' => [['uid'], ['_route_mapping' => ['uid' => 'booking'], '_controller' => 'App\\Controller\\BookingController::show'], [], [['variable', '/', '[^/]++', 'uid', true], ['text', '/booking']], [], [], []],
    'App\Controller\TripController::index' => [[], ['_controller' => 'App\\Controller\\TripController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\TripController::show' => [['slug'], ['_route_mapping' => ['slug' => 'trip'], '_controller' => 'App\\Controller\\TripController::show'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/trip']], [], [], []],
];
